const ExcelJS = require('exceljs');

const HEADER_FILL = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF1E3A5F' },
};

const HEADER_FONT = {
  bold: true,
  color: { argb: 'FFFFFFFF' },
  name: 'Calibri',
  size: 11,
};

const TITLE_FONT = {
  bold: true,
  name: 'Calibri',
  size: 16,
  color: { argb: 'FF1E3A5F' },
};

function applyColumnWidths(sheet, columns) {
  columns.forEach((column, index) => {
    const headerLength = String(column.header || '').length;
    const width = Math.min(40, Math.max(column.width || 14, headerLength + 2));
    sheet.getColumn(index + 1).width = width;
  });
}

function setCellValue(cell, value, type) {
  if (value === null || value === undefined || value === '') {
    cell.value = null;
    return;
  }

  if (type === 'number') {
    const num = Number(value);
    cell.value = Number.isFinite(num) ? num : null;
    cell.numFmt = '#,##0.00';
    return;
  }

  if (type === 'integer') {
    const num = Number(value);
    cell.value = Number.isFinite(num) ? num : null;
    cell.numFmt = '#,##0';
    return;
  }

  if (type === 'date' || type === 'datetime') {
    const date = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(date.getTime())) {
      cell.value = String(value);
      return;
    }
    cell.value = date;
    cell.numFmt = type === 'datetime' ? 'yyyy-mm-dd hh:mm' : 'yyyy-mm-dd';
    return;
  }

  cell.value = value;
}

function writeMeta(sheet, { title, generatedAt, generatedBy, scopeLabel }) {
  sheet.mergeCells('A1:D1');
  sheet.getCell('A1').value = 'SAMS Nepal';
  sheet.getCell('A1').font = TITLE_FONT;

  sheet.mergeCells('A2:D2');
  sheet.getCell('A2').value = title;
  sheet.getCell('A2').font = { bold: true, name: 'Calibri', size: 13 };

  sheet.mergeCells('A3:D3');
  sheet.getCell('A3').value = `Generated: ${generatedAt}`;
  sheet.getCell('A3').font = { name: 'Calibri', size: 10, color: { argb: 'FF444444' } };

  if (scopeLabel) {
    sheet.mergeCells('A4:D4');
    sheet.getCell('A4').value = `Scope: ${scopeLabel}`;
    sheet.getCell('A4').font = { name: 'Calibri', size: 10, color: { argb: 'FF444444' } };
  }

  if (generatedBy) {
    sheet.mergeCells('A5:D5');
    sheet.getCell('A5').value = `Generated by: ${generatedBy}`;
    sheet.getCell('A5').font = { name: 'Calibri', size: 10, color: { argb: 'FF444444' } };
  }
}

function writeTable(sheet, columns, rows, startRow) {
  const headerRow = sheet.getRow(startRow);
  columns.forEach((column, index) => {
    const cell = headerRow.getCell(index + 1);
    cell.value = column.header;
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
    cell.alignment = { vertical: 'middle', horizontal: 'left', wrapText: true };
  });
  headerRow.height = 20;

  rows.forEach((row, rowIndex) => {
    const excelRow = sheet.getRow(startRow + 1 + rowIndex);
    columns.forEach((column, colIndex) => {
      const cell = excelRow.getCell(colIndex + 1);
      setCellValue(cell, row[column.key], column.type);
      cell.alignment = { vertical: 'top', wrapText: column.wrap === true };
    });
  });

  applyColumnWidths(sheet, columns);
  sheet.views = [{ state: 'frozen', ySplit: startRow }];
}

async function buildExcelBuffer({ title, generatedAt, generatedBy, scopeLabel, sheets }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'SAMS Nepal';
  workbook.created = new Date();
  workbook.modified = new Date();

  const definitions = sheets && sheets.length ? sheets : [{ name: 'Report', columns: [], rows: [] }];

  definitions.forEach((definition) => {
    const sheet = workbook.addWorksheet(definition.name.slice(0, 31), {
      pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, paperSize: 9 },
    });
    writeMeta(sheet, { title, generatedAt, generatedBy, scopeLabel });
    writeTable(sheet, definition.columns || [], definition.rows || [], 7);

    if (!definition.rows || definition.rows.length === 0) {
      sheet.getCell('A8').value = 'No records for the current scope and filters.';
      sheet.getCell('A8').font = { italic: true, color: { argb: 'FF666666' } };
    }
  });

  return workbook.xlsx.writeBuffer();
}

module.exports = {
  buildExcelBuffer,
};
