const PDFDocument = require('pdfkit');

const MARGIN = 36;
const FOOTER_HEIGHT = 32;
const HEADER_COLOR = '#1E3A5F';

function contentBottom(doc) {
  return doc.page.height - MARGIN - FOOTER_HEIGHT;
}

function contentWidth(doc) {
  return doc.page.width - MARGIN * 2;
}

function wrapText(doc, text, width, fontSize) {
  const value = text === null || text === undefined ? '' : String(text);
  if (!value) {
    return [''];
  }
  doc.font('Helvetica').fontSize(fontSize);
  return doc.heightOfString
    ? value.split('\n').flatMap((line) => {
        const words = line.split(/\s+/);
        const lines = [];
        let current = '';
        words.forEach((word) => {
          const next = current ? `${current} ${word}` : word;
          if (doc.widthOfString(next) <= width) {
            current = next;
          } else {
            if (current) {
              lines.push(current);
            }
            if (doc.widthOfString(word) <= width) {
              current = word;
            } else {
              let chunk = '';
              for (const ch of word) {
                if (doc.widthOfString(chunk + ch) <= width) {
                  chunk += ch;
                } else {
                  if (chunk) {
                    lines.push(chunk);
                  }
                  chunk = ch;
                }
              }
              current = chunk;
            }
          }
        });
        if (current) {
          lines.push(current);
        }
        return lines.length ? lines : [''];
      })
    : [value];
}

function drawHeader(doc, meta) {
  const width = contentWidth(doc);
  doc.x = MARGIN;
  doc.y = MARGIN;
  doc.font('Helvetica-Bold').fontSize(14).fillColor(HEADER_COLOR).text('SAMS Nepal', MARGIN, MARGIN, { width });
  doc.font('Helvetica-Bold').fontSize(11).fillColor('#111111').text(meta.title, { width });
  doc.font('Helvetica').fontSize(8).fillColor('#444444');
  doc.text(`Generated: ${meta.generatedAt}`, { width });
  if (meta.scopeLabel) {
    doc.text(`Scope: ${meta.scopeLabel}`, { width });
  }
  if (meta.generatedBy) {
    doc.text(`Generated by: ${meta.generatedBy}`, { width });
  }
  const y = doc.y + 6;
  doc.save().strokeColor(HEADER_COLOR).lineWidth(1.2).moveTo(MARGIN, y).lineTo(MARGIN + width, y).stroke().restore();
  doc.y = y + 10;
}

function addFooters(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    const width = contentWidth(doc);
    const y = doc.page.height - MARGIN - 10;
    doc.font('Helvetica').fontSize(8).fillColor('#555555');
    doc.text('Confidential — Government of Nepal / School Asset Management', MARGIN, y, {
      width: width - 90,
      align: 'left',
      lineBreak: false,
    });
    doc.text(`Page ${i + 1} of ${range.count}`, MARGIN + width - 90, y, {
      width: 90,
      align: 'right',
      lineBreak: false,
    });
  }
}

function ensureSpace(doc, meta, needed) {
  if (doc.y + needed <= contentBottom(doc)) {
    return;
  }
  doc.addPage();
  drawHeader(doc, meta);
}

function drawTable(doc, meta, columns, rows, { fontSize = 8 } = {}) {
  const width = contentWidth(doc);
  const totalWeight = columns.reduce((sum, column) => sum + (column.width || 1), 0);
  const colWidths = columns.map((column) => ((column.width || 1) / totalWeight) * width);
  const lineHeight = fontSize + 3;

  const drawHeaderRow = () => {
    const headerLines = columns.map((column, index) => wrapText(doc, column.header, colWidths[index] - 6, fontSize));
    const headerHeight = Math.max(...headerLines.map((lines) => lines.length)) * lineHeight + 6;
    ensureSpace(doc, meta, headerHeight);
    const startY = doc.y;
    let x = MARGIN;
    columns.forEach((column, index) => {
      doc.save().rect(x, startY, colWidths[index], headerHeight).fill(HEADER_COLOR).restore();
      doc.font('Helvetica-Bold').fontSize(fontSize).fillColor('#FFFFFF');
      headerLines[index].forEach((line, lineIndex) => {
        doc.text(line, x + 3, startY + 3 + lineIndex * lineHeight, {
          width: colWidths[index] - 6,
          lineBreak: false,
        });
      });
      x += colWidths[index];
    });
    doc.y = startY + headerHeight;
  };

  drawHeaderRow();

  if (!rows.length) {
    ensureSpace(doc, meta, 20);
    doc.font('Helvetica-Oblique').fontSize(9).fillColor('#666666').text('No records for the current scope and filters.', MARGIN, doc.y, {
      width,
    });
    return;
  }

  rows.forEach((row, rowIndex) => {
    const cellLines = columns.map((column, index) =>
      wrapText(doc, row[column.key], colWidths[index] - 6, fontSize)
    );
    const rowHeight = Math.max(...cellLines.map((lines) => Math.max(lines.length, 1))) * lineHeight + 4;

    if (doc.y + rowHeight > contentBottom(doc)) {
      doc.addPage();
      drawHeader(doc, meta);
      drawHeaderRow();
    }

    const startY = doc.y;
    if (rowIndex % 2 === 0) {
      doc.save().rect(MARGIN, startY, width, rowHeight).fill('#F4F7FA').restore();
    }
    let x = MARGIN;
    columns.forEach((column, index) => {
      doc.font('Helvetica').fontSize(fontSize).fillColor('#111111');
      cellLines[index].forEach((line, lineIndex) => {
        doc.text(line, x + 3, startY + 2 + lineIndex * lineHeight, {
          width: colWidths[index] - 6,
          lineBreak: false,
        });
      });
      x += colWidths[index];
    });
    doc.save().strokeColor('#D0D7DE').lineWidth(0.4).rect(MARGIN, startY, width, rowHeight).stroke().restore();
    doc.y = startY + rowHeight;
  });
}

function drawKeyValues(doc, meta, items) {
  const width = contentWidth(doc);
  items.forEach((item) => {
    ensureSpace(doc, meta, 16);
    doc.font('Helvetica-Bold').fontSize(9).fillColor('#1E3A5F').text(item.label, MARGIN, doc.y, {
      width: width * 0.55,
      continued: true,
    });
    doc.font('Helvetica').fillColor('#111111').text(String(item.value ?? ''), {
      width: width * 0.45,
      align: 'right',
    });
  });
}

function bufferFromDocument(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

async function buildPdfBuffer({ title, generatedAt, generatedBy, scopeLabel, layout = 'portrait', sections }) {
  const doc = new PDFDocument({
    size: 'A4',
    layout: layout === 'landscape' ? 'landscape' : 'portrait',
    margin: MARGIN,
    bufferPages: true,
    info: {
      Title: `SAMS Nepal — ${title}`,
      Author: 'SAMS Nepal',
      Creator: 'SAMS Nepal',
    },
  });

  const done = bufferFromDocument(doc);
  const meta = { title, generatedAt, generatedBy, scopeLabel };
  drawHeader(doc, meta);

  (sections || []).forEach((section, index) => {
    if (index > 0) {
      doc.moveDown(0.8);
    }
    if (section.heading) {
      ensureSpace(doc, meta, 18);
      doc.font('Helvetica-Bold').fontSize(11).fillColor(HEADER_COLOR).text(section.heading, MARGIN, doc.y, {
        width: contentWidth(doc),
      });
      doc.moveDown(0.3);
    }
    if (section.kind === 'kpis') {
      drawKeyValues(doc, meta, section.items || []);
    } else {
      drawTable(doc, meta, section.columns || [], section.rows || [], { fontSize: section.fontSize || 8 });
    }
  });

  addFooters(doc);
  doc.end();
  return done;
}

module.exports = {
  buildPdfBuffer,
};
