const PERMISSIONS = {
  MUNICIPALITIES_READ: 'municipalities:read',
  MUNICIPALITIES_WRITE: 'municipalities:write',
  SCHOOLS_READ: 'schools:read',
  SCHOOLS_WRITE: 'schools:write',
  ASSETS_READ: 'assets:read',
  ASSETS_WRITE: 'assets:write',
  ASSETS_DELETE: 'assets:delete',
  CATEGORIES_READ: 'categories:read',
  CATEGORIES_WRITE: 'categories:write',
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  REPORTS_READ: 'reports:read',
  DASHBOARD_READ: 'dashboard:read',
  TRANSFERS_READ: 'transfers:read',
  TRANSFERS_REQUEST: 'transfers:request',
  TRANSFERS_APPROVE: 'transfers:approve',
  MAINTENANCE_READ: 'maintenance:read',
  MAINTENANCE_REQUEST: 'maintenance:request',
  MAINTENANCE_APPROVE: 'maintenance:approve',
  HISTORY_READ: 'history:read',
};

const ROLES = {
  STATE_ADMIN: 'state_admin',
  MUNICIPAL_OFFICER: 'municipal_officer',
  SCHOOL_ADMIN: 'school_admin',
};

const ROLE_PERMISSIONS = {
  [ROLES.STATE_ADMIN]: [
    PERMISSIONS.MUNICIPALITIES_READ,
    PERMISSIONS.MUNICIPALITIES_WRITE,
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.SCHOOLS_WRITE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.ASSETS_WRITE,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.CATEGORIES_WRITE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_REQUEST,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_REQUEST,
    PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.HISTORY_READ,
  ],
  [ROLES.MUNICIPAL_OFFICER]: [
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_APPROVE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.HISTORY_READ,
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.SCHOOLS_READ,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.ASSETS_WRITE,
    PERMISSIONS.ASSETS_DELETE,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_REQUEST,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_REQUEST,
    PERMISSIONS.HISTORY_READ,
  ],
};

function resolvePermissions(roleSlug, storedPermissions) {
  if (Array.isArray(storedPermissions) && storedPermissions.length > 0) {
    return storedPermissions;
  }
  return ROLE_PERMISSIONS[roleSlug] || [];
}

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  resolvePermissions,
};
